name: ehjerterehab_crew_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - crewai
    - crewai-tools
    - python-dotenv
    - langchain-google-genai
    - jupyter

# conda env create -f environment.yml --name ehjerterehab_crew_env