#  A CrewAI demo for the eCardiacRehab project


- A.L. 2025-05-25 (`eCardiacRehab.ipynb` with Gemini 2.5 Pro Preview and DeepResearch) 

   - Using the `ecardiacrehab_crew_env` defined below 

```bash
# Create a simple conda environment first
conda create -n ecardiacrehab_crew_env python=3.12
conda activate ecardiacrehab_crew_env

# Install packages individually with version constraints
pip install "crewai>=0.121.0"
pip install "crewai-tools>=0.4.0" 
# pip install "langchain-google-genai>=1.0.0"
pip install "python-dotenv>=1.0.0"
pip install "jupyter>=1.0"

# pip install --upgrade langchain-google-genai
```

## eCardiacRehab

In the project [eCardiacRehab](https://www.helse-bergen.no/en/procard/ecardiacrehab) (eHjerteRehab), a new digital cardiac rehabilitation will be developed and tested for patients who have undergone percutaneous coronary intervention. eCardiacRehab is a digital program that patients with coronary artery disease follow throughout their rehabilitation, at home in their own living room. This is a multimodal and interdisciplinary innovation and research project, with different work packages and many stakeholders involved.

**Purpose:** To demonstrate conceptually how a team of AI agents can collaborate on a task relevant to personalized rehabilitation in eHjerteRehab, using the CrewAI framework. This example is simplified and uses simulated data for illustrative purposes.

-----

### **Prompt 1 to a local LLM installed on a MacBook Pro**:

`% ollama run gemma3:27b "Explain CrewAI to a medical doctor"` 

### CrewAI: A Breakdown for a Medical Doctor

  

Okay, Doctor, let's talk about CrewAI. Think of it as a way to **automate 
complex tasks by simulating a team of AI "agents" working together**. It's 
not a diagnostic tool, nor does it replace clinical judgment. Instead, 
it's a framework for building automated workflows, and I'll explain it in 
a way that hopefully maps to your understanding of how teams function in a 
hospital setting.

**Here's the core concept:**

Instead of asking a single, large language model (like ChatGPT) to do 
everything, CrewAI lets you define **multiple AI "agents," each with a 
specific role, goal, and skillset.** These agents then *collaborate* to 
achieve a larger objective.

**Think of it like this:**

Instead of asking one doctor to both diagnose a patient, research 
treatment options, and then file the insurance claims, you'd have:

* **A Diagnostic Agent:** Specializes in analyzing patient data and 
generating potential diagnoses.
* **A Research Agent:** Dedicated to searching medical literature for the 
latest treatment protocols.
* **An Administrative Agent:** Focused on handling insurance paperwork and 
billing.

**How it works (simplified):**

1. **You define the "Crew":** You create agents, each with:
    * **Role:**  A description of the agent's expertise (e.g., "Medical 
Researcher," "Data Analyst," "Report Writer").
    * **Goal:** A specific objective for that agent (e.g., "Find the 
latest clinical trials for stage 3 melanoma").
    * **Tools:** Access to specific resources – this is key.  These could 
include:
        * **Google Search:** For information retrieval.
        * **Web Browsers:** To access websites and databases.
        * **APIs:** To interact with other software (e.g., electronic 
health records - *this is where it gets really interesting, but also 
complex – more on that later*).
        * **Calculators/Scripting:** For data analysis.

2. **You define a "Task":** You give the crew a larger task to accomplish 
(e.g., "Develop a comprehensive treatment plan for a patient with a rare 
genetic disorder").

3. **The Crew Collaborates:**  CrewAI manages the communication and 
workflow between the agents. They essentially “talk” to each other, share 
information, and delegate tasks until the overall goal is met. 

**Here's how this could be applied (potential use cases, keeping in mind 
early stage):**

* **Literature Reviews:** Automate the process of summarizing a large body 
of medical research on a specific topic.
* **Clinical Trial Matching:**  Identify relevant clinical trials for 
patients based on their diagnosis and medical history.
* **Report Generation:**  Create draft summaries of patient cases for 
presentations or consultations.
* **Data Analysis:** Extract and analyze data from various sources (EHRs, 
research databases) to identify trends or patterns.
* **Prior Authorization Assistance:**  Help automate the process of 
obtaining prior authorization for medications.

**Important Considerations (especially for a medical professional):**

* **Not a Substitute for Clinical Judgment:** This is absolutely crucial.  
CrewAI *assists*, it does not *replace* a doctor’s expertise.  All outputs 
*must* be reviewed and validated by a qualified healthcare professional.
* **Data Privacy & Security:**  Working with patient data requires strict 
adherence to HIPAA and other privacy regulations. Implementing CrewAI in a 
clinical setting requires careful consideration of data security and 
access controls.
* **Accuracy & Reliability:** LLMs are prone to "hallucinations" (making 
up information).  Thorough validation of all outputs is essential.
* **Integration with EHRs (future potential):**  While currently complex, 
the real power lies in integrating CrewAI with electronic health records. 
This would allow agents to access and analyze patient data in real-time, 
but presents significant challenges related to data interoperability, 
security, and privacy.
* **Explainability:**  Understanding *how* an AI arrived at a conclusion 
is critical in healthcare. This can be a challenge with complex AI 
systems.



**In essence, CrewAI is a framework for building automated workflows using 
AI agents. It's about breaking down complex tasks into smaller, more 
manageable components and assigning them to specialized agents.  It's 
still in its early stages, but it has the potential to streamline certain 
administrative and research tasks, freeing up medical professionals to 
focus on patient care.**



Do you have any specific areas of medical practice you're thinking about?  
I can try to illustrate how CrewAI might be applied to those scenarios.  
I'm also happy to address any concerns you have regarding safety, privacy, 
or ethical considerations.

### **Prompt 2 to a local LLM installed on a MacBook Pro**:

`% ollama run gemma3:27b "Explain the role of rehabilitation of patients who have undergone percutaneous coronary intervention"`  

In [1]:
# !ollama run gemma3:27b "Explain the role of rehabilitation of patients who have undergone percutaneous coronary intervention"

### Rehabilitation After Percutaneous Coronary Intervention (PCI)

#### A Comprehensive Explanation by `gemma3:27b` (after 1 min 9 sec):

Percutaneous Coronary Intervention (PCI), often referred to as angioplasty 
with stent placement, is a life-saving procedure for people with narrowed c
coronary arteries. However, the procedure itself is just *one* step in impr
improving a patient's heart health. **Cardiac rehabilitation** is a 
*crucial* component of long-term success following PCI. Here's a breakdown 
of its role, encompassing phases, benefits, and key components:

**Why is Rehabilitation Needed After PCI?**

PCI opens blocked arteries, restoring blood flow to the heart. However, it 
*doesn't* fix the underlying disease (atherosclerosis). Rehabilitation addr
addresses this and helps patients:

* **Reduce future cardiac events:**  Heart attack, stroke, repeat procedure
procedures.
* **Improve functional capacity:**  Ability to perform daily activities wit
without shortness of breath or chest pain.
* **Manage risk factors:** Control cholesterol, blood pressure, diabetes, a
and weight.
* **Improve psychological well-being:** Address anxiety, depression, and fe
fear associated with heart disease.
* **Optimize medication adherence:** Understand and take medications correc
correctly.
* **Promote a heart-healthy lifestyle:**  Diet, exercise, and stress manage
management.




**Phases of Cardiac Rehabilitation After PCI:**

Cardiac rehab programs are typically structured into phases, though the spe
specifics can vary between facilities.

**1. Phase I:  Inpatient/Hospital Phase (Immediately Post-PCI)**

* **Timing:** Begins in the hospital, usually the day after PCI.
* **Focus:**  Gradual mobilization, monitoring for complications (bleeding,
(bleeding, arrhythmia), education about:
    * PCI procedure and what to expect.
    * Medications – purpose, dosage, side effects.
    * Wound care (catheter insertion site).
    * Early warning signs to report to the doctor.
    * Initial activity restrictions.
* **Activities:**  Short walks, simple range-of-motion exercises, breathing
breathing exercises.  The goal is to prevent deconditioning while the patie
patient recovers from the procedure.

**2. Phase II: Outpatient/Supervised Exercise Phase (Weeks 1-12 post-PCI)**
post-PCI)**

* **Timing:** Begins 1-2 weeks after discharge from the hospital. 
* **Focus:**  This is the core of the rehab program. It’s *supervised* exer
exercise, with ECG monitoring and guidance from a team of healthcare profes
professionals (cardiac nurses, exercise physiologists, etc.).
* **Activities:** 
    * **Aerobic exercise:**  Walking, cycling, treadmill. Intensity is care
carefully progressed based on heart rate response and symptoms.
    * **Resistance training:**  Light weights or resistance bands to streng
strengthen muscles.
    * **Flexibility exercises:**  Stretching to improve range of motion.
    * **Education:**  Detailed sessions on risk factor modification (diet, 
smoking cessation, weight management), stress reduction, and medication adh
adherence.
* **Frequency:** Typically 2-3 sessions per week, lasting 30-60 minutes eac
each.

**3. Phase III:  Maintenance/Community Phase (Long-Term)**

* **Timing:**  Starts after completion of Phase II.
* **Focus:**  The patient continues exercise independently, applying the kn
knowledge and skills learned in the previous phases. The goal is to maintai
maintain a heart-healthy lifestyle for life.
* **Activities:**
    *  Continuing regular exercise (walking, jogging, swimming, cycling)
    *  Adhering to a heart-healthy diet.
    *  Managing stress through relaxation techniques.
    *  Regular check-ups with their cardiologist.
    *  May involve joining community-based exercise programs or fitness cla
classes.




**Components of a Comprehensive Cardiac Rehabilitation Program:**

* **Medical Evaluation:**  Before starting, a thorough medical assessment i
is performed to determine exercise capacity and identify any limitations.
* **Exercise Prescription:** An individualized exercise plan is developed b
based on the patient’s needs and abilities.
* **Education:**  Covers a range of topics, including:
    * Heart disease basics
    * Risk factor management (cholesterol, blood pressure, diabetes)
    * Heart-healthy eating
    * Smoking cessation
    * Stress management
    * Medication adherence
* **Psychological Support:**  Addresses anxiety, depression, and fear assoc
associated with heart disease. Counseling or support groups may be offered.
offered.
* **Nutritional Counseling:**  Registered dietitians provide guidan
guidance on creating a heart-healthy diet.
* **Behavioral Modification:**  Helps patients adopt and maintain healthy h
habits.



**Benefits of Cardiac Rehabilitation After PCI:**

* **Reduced mortality:** Studies show a significant reduction in death rate
rates among patients who participate in cardiac rehab.
* **Reduced hospital readmissions:** Rehab decreases the likelihood of bein
being readmitted to the hospital for cardiac events.
* **Improved quality of life:** Patients report feeling more energetic, les
less anxious, and better able to perform daily activities.
* **Increased exercise capacity:** Patients can walk further and perform mo
more strenuous activities without experiencing symptoms.
* **Better control of risk factors:**  Rehab helps patients lower their cho
cholesterol, blood pressure, and weight.
* **Enhanced self-efficacy:** Patients feel more confident in their ability
ability to manage their heart health.

**Who Should Participate in Cardiac Rehabilitation?**

Generally, most patients who have undergone PCI *are* candidates for cardia
cardiac rehabilitation, unless they have a medical contraindication (like u
unstable angina, severe uncontrolled arrhythmia, or a debilitating illness)
illness).  



**Important Note:**  Cardiac rehabilitation isn't a one-size-fits-all progr
program.  The program is individualized to meet the specific needs of each 
patient.  It’s *crucial* to discuss cardiac rehabilitation with your cardio
cardiologist and ask about available programs in your area.  




**Resources:**

* **American Association of Cardiovascular and Pulmonary Rehabilitation (AA
(AACVPR):**  [https://www.aacvpr.org/](https://www.aacvpr.org/)
* **American Heart Association:** [https://www.heart.org/](https://www.hear
[https://www.heart.org/](https://www.heart.org/)




Disclaimer: I am an AI chatbot and cannot provide medical advice. This info
information is for general knowledge and informational purposes only, and d
does not constitute medical advice. It is essential to consult with a quali
qualified healthcare professional for any health concerns or before making 
any decisions related to your health or treatment.

### **Prompt 3 to a local LLM installed on a MacBook Pro**:

`% ollama run gemma3:27b "Forklar betydningen rehabilitering av pasienter som har gjennomgått perkutan koronarintervensjon (svar på nynorsk)"`  

In [2]:
# !ollama run gemma3:27b "Forklar betydningen rehabilitering av pasienter som har gjennomgått perkutan koronarintervensjon (svar på nynorsk)"
# ...
# Etter 41.5 sekunder:

### Rehabilitering etter perkutan koronarintervensjon (PCI) – forklart på nynorsk

Rehabilitering etter PCI, som oftast vert kalla ballongutviding eller stent
stentoperasjon, er ein viktig del av å bli betre etter å ha fått behandling
behandling for hjarteproblemer. Det handlar om meir enn berre å fikse sjølv
sjølve blokkeringa i hjartet. Det er ein heilskapleg prosess som skal hjelp
hjelpe deg med å kome tilbake til eit aktivt og godt liv.

**Kva inneber rehabiliteringa?**

Rehabiliteringa er ikkje berre for dei som har hatt eit hjarteinfarkt, men 
også for dei som har fått PCI for å lindre brystsmerter (angina). Programme
Programmet er individuelt tilpassa, men kan vanlegvis innehalde:

* **Medisinsk overvåking:** Legar og sjukskøtarar følgjer nøye med på korle
korleis du responderer på medisinen og korleis hjartet fungerer.
* **Fysisk trening:**  Dette er ein gradvis opptrapping av fysisk aktivitet
aktivitet, under tilsyn av ein fysioterapeut eller spesialutdanna helsepers
helsepersonell. Målet er å styrke hjartet, forbetre kondisjon og auke energ
energien.
* **Hjartevenleg kosthald:**  Du får råd om eit kosthald som er sunt for hj
hjartet, med fokus på å redusere kolesterol, fett og salt.
* **Psykisk støtte:**  Mange opplever stress, angst eller depresjon etter h
hjarteproblemer. Rehabiliteringa kan inkludere samtaler med psykolog eller 
anna helsepersonell for å takle desse utfordringane.
* **Livsstilsendringar:**  Du får hjelp til å endre vanar som kan auke risi
risikoen for nye hjarteproblem, som røyking, mangel på fysisk aktivitet og 
stress.
* **Opplæring:** Du lærer om hjarte sjukdom, medisinar, korleis du kjenner 
igjen symptom og korleis du kan førebyggje nye problem.

**Kvifor er rehabilitering viktig?**

* **Reduserer risikoen for nye hjarteproblem:** Rehabilitering kan redusere
redusere risikoen for å få eit nytt hjarteinfarkt, anginasmterter eller beh
behov for ny behandling.
* **Forbetrar livskvaliteten:**  Det hjelper deg med å kome tilbake til eit
eit aktivt liv, redusere symptom og auke energien.
* **Aukar sjølvstendet:**  Du lærer å ta vare på eige helse og førebyggje f
framtidige problem.
* **Reduserer angst og depresjon:**  Psykisk støtte kan hjelpe deg med å ta
takle dei emosjonelle utfordringane etter hjarteproblemer.
* **Gjør deg i stand til å førebyggje komplikasjonar:** Du får kunnskap om 
korleis du skal handle dersom du opplever ubehage eller nye symptom.

**Når startar rehabiliteringa?**

Rehabilitering kan starte allereie på sjukehus, kort tid etter PCI. Det kan
kan også fortsette som eit poliklinisk program, heime eller i lokale rehabi
rehabiliteringssenter. Legen din vil vurdere kva som er best for deg.

**Oppsummert:**

Rehabilitering etter PCI er ein viktig investering i di eiga helse. Det han
handlar om å hjelpe deg med å kome tilbake til eit aktivt og meningsfullt l
liv, og redusere risikoen for nye hjarteproblem. Det er ein heilskapleg pro
prosess som inkluderer fysisk trening, kosthaldsråd, psykisk støtte og oppl
opplæring.  Snakk med legen din om kva rehabiliteringsprogram som er best f
for deg.

-----

## CrewAI: Understanding the Imports and LLM Configuration

#### Core CrewAI Components
The imports at the top of our notebook bring in the essential building blocks for creating multi-agent workflows:

- **`Agent`**: Represents an individual AI agent with a specific role, goal, and backstory. Each agent is specialized for particular tasks (e.g., analyzing vital signs, checking symptoms).

- **`Task`**: Defines specific work to be performed by an agent. Tasks have descriptions, expected outputs, and can depend on other tasks.

- **`Crew`**: Orchestrates multiple agents and their tasks. It manages the workflow, ensures tasks are executed in the right order, and handles communication between agents.

- **`Process`**: Defines how tasks are executed - either sequentially (one after another) or hierarchically (with a manager agent coordinating others).

#### Tools for Enhanced Capabilities

- **`CodeInterpreterTool`**: Allows agents to execute Python code, perform calculations, create visualizations, and work with data. This is particularly useful for the Vital Signs Analyzer agent to perform numerical analysis.

- **Other available tools**: CrewAI offers many tools like `CSVSearchTool`, `WebSearchTool`, and `DatabaseTool` for different data sources and operations.

#### Environment Management

- **`dotenv`**: Securely manages API keys and configuration settings through environment variables. This prevents hardcoding sensitive information directly in the code.

#### LLM Configuration - The Brain Behind the Agents
CrewAI agents require a Large Language Model (LLM) to power their reasoning and decision-making capabilities. The LLM serves as the "brain" that:

- Understands task instructions
- Processes input data  
- Makes decisions about what actions to take
- Generates responses and outputs

**Example configurations:**

```python
# Option 1: OpenAI GPT (requires OPENAI_API_KEY)
from langchain_openai import ChatOpenAI
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)

# Option 2: Google Gemini (requires GOOGLE_API_KEY) - Used in this demo
from langchain_google_genai import ChatGoogleGenerativeAI  
llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash-latest",
    temperature=0.2,
    google_api_key=os.getenv("GOOGLE_API_KEY")
)
```

### 🔐 Security Best Practices for API Keys
**Never hardcode API keys directly in your code!** Instead:

1. **Create a `.env` file** in your project root:
   ```
   GOOGLE_API_KEY=your_actual_api_key_here
   OPENAI_API_KEY=your_openai_key_here
   ```

2. **Load environment variables** using `load_dotenv()`

3. **Access keys safely** with `os.getenv("GOOGLE_API_KEY")`

4. **Add `.env` to `.gitignore`** to prevent accidental commits to version control

This approach ensures your API keys remain secure while making your code portable across different environments (development, testing, production).

## Setup

In [3]:
# Import necessary libraries
from crewai import LLM, Agent, Task, Crew, Process
from crewai_tools import CodeInterpreterTool # Or other relevant tools like CSVSearchTool
from dotenv import load_dotenv
import os

# Load environment variables (for API keys)
load_dotenv()

# Suppress warnings
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module="langchain_google_genai")

# Configure the LLM (Example using Google's Gemini)
# Check if GEMINI_API_KEY key is available in your.env file or environment
if not os.getenv("GEMINI_API_KEY"):
    raise ValueError("GEMINI_API_KEY not found. Please set it in your .env file or environment variables.")
# Check if OPENAI_API_KEY key is available in your .env file or environment
if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY not found. Please set it in your .env file or environment variables.")

# Configure the Gemini 2.5 Flash model (NOT WORKING)
# model='gemini/gemini-2.5-flash-preview-05-06',  # Not valid model name ...
# Alternatively: openai/gpt-4o-mini (OPENAI_API_KEY=your_openai_api_key)
gemini_flash_llm = LLM(
    model='gemini/gemini-1.5-flash',  # Use the older Gemini 1.5 Flash
    api_key=os.getenv("GEMINI_API_KEY"),
    temperature=0.2  # Adjust temperature as needed
)
openai_llm = LLM(
    model='openai/gpt-4o-mini',  # Use the older GPT-4o-mini
    api_key=os.getenv("OPENAI_API_KEY"),
    temperature=0.2  # Adjust temperature as needed
)

**Alternative Setup**

```bash
# Import necessary libraries
from crewai import Agent, Task, Crew, Process
from crewai_tools import CodeInterpreterTool # Or other relevant tools like CSVSearchTool
from dotenv import load_dotenv
import os

# Load environment variables (for API keys)
load_dotenv()

# Suppress warnings
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module="langchain_google_genai")

# Configure the LLM (Example using OpenAI)
# Ensure GEMINI_API_KEY is set in your.env file or environment
# from langchain_openai import ChatOpenAI
# llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.2)
# For Google Gemini (ensure GEMINI_API_KEY is set):

# Check if API key is available
if not os.getenv("GEMINI_API_KEY"):
    raise ValueError("GEMINI_API_KEY not found. Please set it in your .env file or environment variables.")

from langchain_google_genai import ChatGoogleGenerativeAI
#llm = ChatGoogleGenerativeAI(model="gemini-15-flash-latest",
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash",
                             verbose=True,
                             temperature=0.2,
                             google_api_key=os.getenv("GEMINI_API_KEY"))

# (Optional) Instantiate any tools if needed globally
# e.g., code_interpreter_tool = CodeInterpreterTool(llm=llm)
```

-----

## CrewAI Demo: Personalized Activity Recommendations for eCardiacRehab

#### **Purpose:** 
This Jupyter Notebook example demonstrates how a team of specialized AI agents, built with CrewAI, can collaborate to analyze a (simulated) patient profile and generate personalized activity recommendations with a subsequent ethical assessment. This illustrates a potential application of AI to support personalization in eCardiacRehab.

#### **Scenario:**

1. A `DataInterpreterAgent` analyzes a patient profile to identify key insights.

2. An `ActivityDesignerAgent` uses these insights to suggest rehabilitation activities.

3. An `EthicsAndComplianceAgent` evaluates the recommendations from an ethical and responsible perspective.

#### **Note**: 
This is a conceptual demonstration and does not use real patient data or advanced medical tools.

### Why CrewAI for this demonstration?

The choice of CrewAI for this demonstration is strategic. The eCardiacRehab project is itself a multimodal and interdisciplinary initiative with many stakeholders. CrewAI allows us to mirror this interdisciplinary collaboration model in an AI architecture.

- **Specialized Agents**: Instead of a single, monolithic AI (which can be perceived as a "black box"), CrewAI allows us to define agents with distinct roles, goals, and backstories. This can be compared to how various professional experts (cardiologist, physiotherapist, psychologist, ethicist) collaborate in healthcare.

- **Transparent Process**: By observing the interaction between agents, the AI process becomes potentially more transparent and understandable. One can see how different "expertise areas" (simulated by the agents) contribute to the final result.

- **Making AI Accessible**: Such an agent-based approach can make AI concepts more accessible and less threatening to healthcare personnel and other stakeholders, as it builds on familiar principles of teamwork and shared responsibility. This aligns with eHjerteRehab's goal of modernizing and digitalizing work processes in an understandable way.

------


## Simulated Patient Data: Structure and Description

### **Data Structure Overview**
The simulated patient data is structured as a **list of dictionaries**, where each dictionary represents one cardiac rehabilitation patient's 24-hour monitoring data. This format mimics what might be collected from wearable devices, patient apps, and daily check-ins in a real eCardiacRehab system.

### **Patient Record Fields**
Each patient record contains exactly **5 standardized fields**:

#### **1. `patient_id` (String)**
- **Purpose**: Unique identifier for each patient
- **Format**: "P001", "P002", etc.
- **Usage**: Enables tracking and reporting by patient across all agents

#### **2. `avg_resting_hr_last_24h` (Integer)**
- **Purpose**: Average resting heart rate over the last 24 hours
- **Units**: Beats per minute (bpm)
- **Normal Range**: Typically 60-90 bpm for cardiac patients
- **Clinical Significance**: Elevated resting HR (>90 bpm) may indicate:
  - Medication issues
  - Dehydration
  - Stress or anxiety
  - Potential cardiac complications

#### **3. `max_hr_during_exercise_last_24h` (Integer)**
- **Purpose**: Peak heart rate during any exercise activity in the past 24 hours
- **Units**: Beats per minute (bpm)
- **Expected Range**: 120-170 bpm depending on exercise intensity and patient condition
- **Clinical Significance**: Helps assess exercise tolerance and adherence to prescribed heart rate zones

#### **4. `total_steps_last_24h` (Integer)**
- **Purpose**: Total step count over 24 hours from wearable device
- **Units**: Number of steps
- **Target Range**: Typically 2000+ steps for cardiac rehabilitation patients
- **Clinical Significance**: Low step counts (<2000) may indicate:
  - Reduced mobility
  - Fatigue
  - Fear of exercise
  - Potential complications

#### **5. `reported_symptoms_text` (String)**
- **Purpose**: Free-text patient-reported symptoms and feelings
- **Format**: Natural language descriptions
- **Content**: Includes physical symptoms, emotional state, activity completion
- **Clinical Significance**: Contains critical keywords that may indicate urgent concerns

### **Data Range Analysis in Our Demo**

**Patients with Concerning Vital Signs:**
- **P002**: High resting HR (95 bpm) AND low steps (1800)
- **P004**: Low steps (1500) 
- **P005**: High resting HR (102 bpm)
- **P006**: Very low steps (950)
- **P008**: High resting HR (93 bpm)

**Patients with Concerning Symptoms:**
- **P002**: "chest pain", "dizzy"
- **P004**: "palpitations", "dizziness"
- **P006**: "chest discomfort"
- **P008**: "severe discomfort", "faint"

**Patients with Normal Profiles:**
- **P001**: Normal vitals, positive symptoms
- **P003**: Normal vitals, mild fatigue (not critical)
- **P007**: Normal vitals, excellent symptoms

### **Real-World Data Source Simulation**
In an actual eCardiacRehab system, this data would originate from:
- **Wearable devices** (heart rate, steps) - Fitbit, Apple Watch, Garmin
- **Patient mobile apps** (symptom reporting, daily check-ins)
- **Electronic health records** (patient identifiers, baseline data)
- **Telehealth platforms** (structured questionnaires)

### **Data Processing for AI Agents**
```python
patient_data_summary_str = "\n".join([str(p) for p in patient_data_input])
```

The conversion to string format:
- **Serializes** the structured data for text-based LLM processing
- **Maintains** all field information in a readable format
- **Enables** the `{patient_data_input_str}` placeholder in task descriptions
- **Allows** each agent to access the complete dataset while focusing on their specialized analysis

### **Scalability Considerations**
In a real system, data would come from databases or APIs. This simplified 8-patient dataset demonstrates the concept, but a production eCardiacRehab system would handle:
- **Hundreds or thousands** of patients simultaneously
- **Historical data** tracking trends over weeks/months
- **Additional fields** like medication adherence, sleep quality, weight, blood pressure
- **Real-time streaming** data rather than 24-hour summaries
- **Integration** with hospital systems and clinical workflows

This data structure provides a realistic foundation for demonstrating how AI agents can collaboratively analyze cardiac rehabilitation monitoring data to identify patients requiring immediate attention or intervention.


In [4]:
# Simulated patient data for the demo - following our scenario scheme
patient_data_input = [
    {
        "patient_id": "P001",
        "avg_resting_hr_last_24h": 72,
        "max_hr_during_exercise_last_24h": 135,
        "total_steps_last_24h": 8500,
        "reported_symptoms_text": "Feeling good today. Completed my morning walk without any issues. Energy levels are stable."
    },
    {
        "patient_id": "P002", 
        "avg_resting_hr_last_24h": 95,
        "max_hr_during_exercise_last_24h": 165,
        "total_steps_last_24h": 1800,
        "reported_symptoms_text": "Woke up with some chest pain, but it passed. Feeling a bit dizzy today after climbing stairs."
    },
    {
        "patient_id": "P003",
        "avg_resting_hr_last_24h": 68,
        "max_hr_during_exercise_last_24h": 142,
        "total_steps_last_24h": 5200,
        "reported_symptoms_text": "Overall doing well. Some mild fatigue but nothing concerning. Appetite is good."
    },
    {
        "patient_id": "P004",
        "avg_resting_hr_last_24h": 88,
        "max_hr_during_exercise_last_24h": 158,
        "total_steps_last_24h": 1500,
        "reported_symptoms_text": "Had some palpitations during exercise yesterday. Also experienced dizziness when standing up quickly."
    },
    {
        "patient_id": "P005",
        "avg_resting_hr_last_24h": 102,
        "max_hr_during_exercise_last_24h": 175,
        "total_steps_last_24h": 3200,
        "reported_symptoms_text": "Feeling anxious about my recovery. Some shortness of breath during light activities."
    },
    {
        "patient_id": "P006",
        "avg_resting_hr_last_24h": 75,
        "max_hr_during_exercise_last_24h": 128,
        "total_steps_last_24h": 950,
        "reported_symptoms_text": "Feeling tired, slight chest discomfort during stairs. Had to rest more than usual."
    },
    {
        "patient_id": "P007",
        "avg_resting_hr_last_24h": 82,
        "max_hr_during_exercise_last_24h": 148,
        "total_steps_last_24h": 6800,
        "reported_symptoms_text": "Great day! Completed all my exercises. Feeling stronger and more confident."
    },
    {
        "patient_id": "P008",
        "avg_resting_hr_last_24h": 93,
        "max_hr_during_exercise_last_24h": 170,
        "total_steps_last_24h": 2400,
        "reported_symptoms_text": "Some severe discomfort in my chest area this morning. Also felt faint briefly around noon."
    }
]

# Convert to a string format that can be easily passed to the first agent
patient_data_summary_str = "\n".join([str(p) for p in patient_data_input])


This dataset now includes:

**All required fields from the our scenario:**
- ✅ `patient_id` (e.g., "P001")
- ✅ `avg_resting_hr_last_24h` (integer, e.g., 95 bpm)
- ✅ `max_hr_during_exercise_last_24h` (integer, e.g., 150 bpm) - **newly added**
- ✅ `total_steps_last_24h` (integer, e.g., 1500)
- ✅ `reported_symptoms_text` (string, including example "slight chest discomfort during stairs")

**Realistic exercise heart rate values:**
- Normal range: 128-148 bpm (moderate exercise intensity)
- Elevated: 158-175 bpm (higher intensity, potentially concerning for some patients)
- The values correlate logically with resting HR and patient condition

**Enhanced symptom text:**
- P006 now includes the exact example phrase: "slight chest discomfort during stairs"
- Maintains the mix of flagged symptoms and normal reports

This dataset perfectly matches the schema described in our scenario and will work seamlessly with your CrewAI agents for the automated patient data triage demonstration!


------

## Agent Definitions – Our AI Team

We now define our three AI agents. Each agent receives a specific `role`, a `goal`, and a `backstory`. These elements are not merely descriptive; they function as advanced instructions (prompts) that shape how the LLM performs the agent's tasks.

A well-crafted `backstory` is crucial for instructing the LLM to adopt a specific professional identity and approach, which directly impacts the quality and relevance of the agent's output. This is especially important in specialized domains like healthcare.

We set `verbose=False` to keep the execution tidy, but this can be changed to `True` to follow the agents' "thought process" during execution. `allow_delegation=False` means that the agents cannot delegate tasks to other agents in this simple scenario.

**Vital Signs Analyzer Agent** functions as a specialist for monitoring vital signs. This agent is trained to identify concerning readings in patient data, specifically high resting heart rate (>90 bpm) and low activity (<2000 steps).

**Symptom Checker Agent** takes the role of a symptom screener that analyzes patient-reported textual symptoms. The agent specializes in detecting critical keywords such as "chest pain", "dizzy", "severe discomfort", "palpitations", and "faint".

**Clinical Reporter Agent** functions as a clinical report generator that compiles findings from the other agents into a concise Markdown report. This agent presents information clearly and efficiently for healthcare professionals, providing an overview of flagged vital signs and symptoms for each patient.

In [5]:
# Define the Vital Signs Analyzer Agent
vital_signs_analyzer = Agent(
    role='Vital Signs Monitoring Specialist',
    goal='Analyze patient vital signs data (resting HR, steps) to identify and flag any readings that are concerning. Resting HR > 90 bpm is high. Total steps < 2000 is low.',
    backstory='An AI assistant dedicated to meticulously reviewing numerical health data from cardiac rehabilitation patients, trained to spot deviations that might require further attention.',
    llm=openai_llm,
    verbose=True, #True,
    allow_delegation=False
    # tools=[code_interpreter_tool] # If using CodeInterpreterTool instantiated globally
)

# Define the Symptom Checker Agent
symptom_checker = Agent(
    role='Patient Symptom Screener',
    goal="Review patient-reported textual symptoms to identify and flag mentions of critical keywords such as 'chest pain', 'dizzy', 'dizziness', 'severe discomfort', 'palpitations', 'faint'.",
    backstory='An AI assistant focused on understanding patient language, specifically trained to detect urgent symptom descriptions in cardiac patient reports.',
    llm=openai_llm,
    verbose=True, #True,
    allow_delegation=False
)

# Define the Clinical Reporter Agent
clinical_reporter = Agent(
    role='Clinical Summary Generator',
    goal='Compile the findings from vital signs analysis and symptom checking into a concise Markdown report. The report should list each patient, any flagged vital signs with values, and any flagged symptoms. If no flags for a patient, state "No immediate concerns noted".',
    backstory='An AI assistant skilled in synthesizing analytical information from multiple sources and presenting it clearly and efficiently in Markdown format for healthcare professionals.',
    llm=openai_llm,
    verbose=True, #True,
    allow_delegation=False
)

## Detailed Agent Analysis

Explaining each agent's configuration: role, goal, backstory shape its behavior. 

- llm assigns the language model 

- verbose=True is crucial for observing the agent's thought process during development and debugging, as it reveals the internal "ReAct" (Reasoning and Acting) loop – the agent's thoughts, the action it decides upon, the input to that action, and the subsequent observation. 
It might end up with extensive recursions and large output of text, therefore we set `verbose=True` in our demo.
- allow_delegation=False is set for simplicity in this demo. 

### Agent Structure and Components

Each of these three agents follows the CrewAI Agent pattern with several key components:

**1. Vital Signs Analyzer Agent**
- **Role**: Acts as a "Vital Signs Monitoring Specialist" - this defines the agent's professional identity
- **Goal**: Provides specific, measurable criteria for what constitutes concerning readings (HR > 90 bpm, steps < 2000)
- **Backstory**: Establishes the agent's expertise context and training focus on cardiac rehabilitation patients
- **Function**: This agent will receive numerical health data and apply the defined thresholds to flag potential issues

**2. Symptom Checker Agent**
- **Role**: Functions as a "Patient Symptom Screener" - focused on natural language processing
- **Goal**: Defines specific keywords to search for in patient text ('chest pain', 'dizzy', 'palpitations', etc.)
- **Backstory**: Emphasizes language understanding and urgent symptom detection capabilities
- **Function**: This agent processes free-text patient reports to identify critical symptoms

**3. Clinical Reporter Agent**
- **Role**: Serves as a "Clinical Summary Generator" - the synthesis and communication specialist
- **Goal**: Specifies the output format (Markdown) and structure (patient-by-patient summary)
- **Backstory**: Highlights skills in information synthesis and professional healthcare communication
- **Function**: This agent takes input from the other two agents and creates a structured report

### The `llm=<llm>` Parameter

The `llm=llm` parameter is crucial - it specifies which Large Language Model each agent will use to process information and generate responses. This parameter:

- **Connects the agent to its "brain"** - the actual AI model that will interpret the role, goal, and backstory
- **Ensures consistency** - all agents use the same underlying model but with different specialized prompts
- **Allows flexibility** - you can assign different models to different agents if needed

### Using Ollama with Gemma 3 27B (a local LLM)

To use a local Ollama model like Gemma 3 27B, you would need to configure the `llm` variable before creating the agents. Here's how:

```python
from langchain_community.llms import Ollama

# Configure Ollama with Gemma 3 27B
llm = Ollama(
    model="gemma3:27b",
    base_url="http://localhost:11434",  # Default Ollama URL
    temperature=0.1,  # Low temperature for consistent medical analysis
    num_predict=1024,  # Maximum tokens to generate
    top_k=10,  # Limits vocabulary for more focused responses
    top_p=0.9   # Nucleus sampling parameter
)
```

**Prerequisites for using Ollama:**
1. Install Ollama on your system
2. Pull the Gemma 3 model: `ollama pull gemma3:27b`
3. Ensure Ollama service is running
4. Install langchain-community: `pip install langchain-community`

**Benefits of using Gemma 3 27B locally:**
- **Privacy**: Patient data never leaves your local environment
- **Cost**: No API fees for model usage
- **Control**: Full control over model parameters and availability
- **Compliance**: Easier to meet healthcare data protection requirements

**Considerations:**
- **Hardware requirements**: Gemma 3 27B requires significant RAM (>= 24 GB recommended)
- **Speed**: Local inference may be slower than cloud APIs
- **Setup complexity**: Requires local model management

The choice of model significantly impacts agent performance, especially for healthcare applications where accuracy and reliability are paramount.

## More info on Ollama Gemma 3 27B

(ChatGPT 4.1-mini)

<a href="https://ollama.com/library/gemma3:27b">
  <img src="https://ollama.com/assets/library/gemma3/b54bf767-f9c5-4284-b551-a49aebe3a3c2" 
       alt="Gemma3" 
       width="300">
</a>

[Gemma 3 27B](https://ollama.com/library/gemma3:27b) is a multimodal large language model developed by Google DeepMind, built upon the Gemini architecture. It is designed to process both text and images, supporting over 140 languages and offering a substantial context window of up to 128,000 tokens. This model is part of the Gemma 3 family, which includes variants with 1B, 4B, 12B, and 27B parameters, each tailored for different computational resources and tasks.([Ollama][1], [Ollama][2], [Ollama][3])

---

### 🧠 Model Overview

Gemma 3 27B is optimized for a range of applications, including question answering, summarization, reasoning, and image understanding. Its multimodal capabilities allow it to interpret and respond to both textual and visual inputs, making it versatile for various AI-driven tasks. The model's architecture has been enhanced to reduce memory usage, particularly in the key-value (KV) cache, by increasing the ratio of local to global attention layers and limiting the span of local attention. This optimization is crucial for handling long-context inputs efficiently.([Ollama][1], [arXiv][4])

---

### ⚙️ Quantization and Performance

To make Gemma 3 27B more accessible on consumer-grade hardware, Google has implemented Quantization Aware Training (QAT). This approach allows the model to maintain performance comparable to half-precision models (BF16) while significantly reducing memory requirements. For instance, the BF16 version of Gemma 3 27B requires approximately 54 GB of VRAM, whereas the Q4\_0 quantized version reduces this to around 17 GB. This reduction enables the model to run on high-end GPUs like the NVIDIA RTX 3090, which has 24 GB of VRAM, making it more feasible for local deployments .([Ollama][1], [Ollama][2], [Google Developers Blog][5])

---

### 🖥️ Running Gemma 3 27B Locally

To run Gemma 3 27B locally, you can use the Ollama framework, which supports the GGUF model format. After installing Ollama, you can execute the model with the following command:([Google AI for Developers][6], [Ollama][7])

```bash
ollama run gemma3:27b
```



For instruction-tuned versions, you might use:([Ollama][1])

```bash
ollama run gemma3:27b-it
```



These models are optimized for various tasks, including instruction following and image-text interactions.([Ollama][1])

---

### 📊 Benchmark Performance

Gemma 3 27B has demonstrated strong performance across several benchmark datasets:([Reddit][8])

* **Reasoning and Logic**: Achieved top-1 accuracy of 78.6% on the MMLU benchmark.
* **Multilingual Understanding**: Scored 75.7% on the Global-MMLU-Lite benchmark.
* **Multimodal Tasks**: Obtained a score of 116 on the COCO captioning task, indicating robust image understanding capabilities.([Ollama][2])

These results position Gemma 3 27B as a competitive model in the landscape of large language models.

---

### 🔧 Considerations for Deployment

* **Hardware Requirements**: While the QAT versions reduce memory usage, deploying Gemma 3 27B still necessitates a high-performance GPU with substantial VRAM.
* **Software Compatibility**: Ensure that your system has the necessary software stack, including compatible versions of Ollama and GPU drivers, to run the model efficiently.
* **Model Access**: Some versions of Gemma 3 27B may require authentication or access permissions, especially those hosted on platforms like Hugging Face.([Google Developers Blog][5])

---

### 🔗 Further Resources

* [Gemma 3 on Ollama](https://ollama.com/library/gemma3%3A27b)
* [Gemma 3 Technical Report](https://arxiv.org/abs/2503.19786)
* [Google Developers Blog on Gemma 3 QAT](https://developers.googleblog.com/en/gemma-3-quantized-aware-trained-state-of-the-art-ai-to-consumer-gpus/)

If you need assistance with specific deployment scenarios or have questions about integrating Gemma 3 27B into your projects, feel free to ask.

[1]: https://ollama.com/eramax/gemma-3-27b-it-qat%3Aq4_0?utm_source=chatgpt.com "eramax/gemma-3-27b-it-qat:q4_0 - Ollama"
[2]: https://ollama.com/library/gemma3%3A27b?utm_source=chatgpt.com "gemma3:27b - Ollama"
[3]: https://www.ollama.com/library/gemma3%3A27b-it-q8_0?utm_source=chatgpt.com "gemma3:27b-it-q8_0"
[4]: https://arxiv.org/abs/2503.19786?utm_source=chatgpt.com "Gemma 3 Technical Report"
[5]: https://developers.googleblog.com/en/gemma-3-quantized-aware-trained-state-of-the-art-ai-to-consumer-gpus/?utm_source=chatgpt.com "Gemma 3 QAT Models: Bringing state-of-the-Art AI to consumer GPUs"
[6]: https://ai.google.dev/gemma/docs/integrations/ollama?utm_source=chatgpt.com "Run Gemma with Ollama | Google AI for Developers - Gemini API"
[7]: https://ollama.com/nidumai/nidum-gemma-3-27b-instruct-uncensored?utm_source=chatgpt.com "nidumai/nidum-gemma-3-27b-instruct-uncensored - Ollama"
[8]: https://www.reddit.com/r/LocalLLaMA/comments/1jb4jcr/difference_in_gemma_3_27b_performance_between_ai/?utm_source=chatgpt.com "Difference in Gemma 3 27b performance between ai studio ... - Reddit"


------

## The `tools` Parameter and Code Interpreter Tool

The commented line `# tools=[code_interpreter_tool]` reveals an important aspect of CrewAI agent capabilities - the ability to equip agents with specialized tools.

### What are Tools in CrewAI?

Tools extend an agent's capabilities beyond simple text processing. They allow agents to:
- Execute code
- Access external APIs
- Perform calculations
- Read/write files
- Search databases
- Make web requests

### The Code Interpreter Tool Specifically

The `CodeInterpreterTool` would give the agent the ability to:
- **Execute Python code dynamically** during task execution
- **Perform complex calculations** on vital signs data
- **Generate visualizations** of patient trends
- **Process data files** (CSV, JSON) containing patient information
- **Validate data integrity** and perform statistical analysis

### Why It's Commented Out

The comment suggests this is optional and depends on whether a `CodeInterpreterTool` has been "instantiated globally." This means:

```python
# You would first need to create the tool:
from crewai_tools import CodeInterpreterTool

code_interpreter_tool = CodeInterpreterTool()

# Then uncomment and use it in the agent:
vital_signs_analyzer = Agent(
    # ... other parameters ...
    tools=[code_interpreter_tool]
)
```

### Practical Benefits for Healthcare Agents

**For the Vital Signs Analyzer:**
- Could calculate statistical measures (mean, std dev) across patient populations
- Generate trend analysis over time
- Create visualizations of heart rate patterns
- Validate data ranges and detect outliers programmatically

**Example use case:**
```python
# The agent could execute code like:
"""
import pandas as pd
import numpy as np

# Calculate rolling average of heart rate
hr_data = [85, 92, 88, 95, 101, 87]
rolling_avg = np.convolve(hr_data, np.ones(3)/3, mode='valid')
flagged = any(hr > 90 for hr in hr_data)
"""
```

### Security and Healthcare Considerations

**Benefits:**
- More sophisticated data analysis capabilities
- Ability to handle complex medical calculations
- Dynamic threshold adjustments based on patient history

**Risks:**
- Code execution introduces security concerns
- Need to ensure executed code doesn't access unauthorized data
- Potential for errors in dynamically generated code
- Compliance with healthcare data protection regulations

### Alternative Approach

Instead of general code execution, you might prefer domain-specific tools:
```python
from custom_tools import VitalSignsValidatorTool, MedicalCalculatorTool

vital_signs_analyzer = Agent(
    # ... other parameters ...
    tools=[VitalSignsValidatorTool(), MedicalCalculatorTool()]
)
```

This provides controlled functionality without the security risks of arbitrary code execution, which is often more appropriate for healthcare applications where data security and predictable behavior are paramount.

--------- 



## Task Definitions: Detailed Breakdown

Here's a comprehensive explanation of each task, showing how they work together in the CrewAI workflow:

### 1. **Vital Analysis Task** (`vital_analysis_task`)

**Assigned Agent:** `vital_signs_analyzer` (Vital Signs Monitoring Specialist)

**Task Description Breakdown:**
- **Input:** Receives the full patient data summary string via `{patient_data_input_str}` placeholder
- **Analysis Criteria:** 
  - Flag patients with **resting heart rate > 90 bpm** 
  - Flag patients with **total steps < 2000**
  - Uses OR logic (either condition triggers a flag)
- **Processing:** Agent systematically reviews each patient's numerical vital signs data
- **Output Requirement:** Must list patient ID + specific flagged values, or note "no flags"

**Expected Output Format:**
```
Patient P001: No vital signs flagged
Patient P002: Flagged - Resting HR: 95 bmp, Total Steps: 1800
Patient P003: No vital signs flagged
...
```

### 2. **Symptom Check Task** (`symptom_check_task`)

**Assigned Agent:** `symptom_checker` (Patient Symptom Screener)

**Task Description Breakdown:**
- **Input:** Same patient data, but focuses on `reported_symptoms_text` field
- **Keyword Detection:** Searches for critical terms:
  - `'chest pain'`
  - `'dizzy'` / `'dizziness'`
  - `'severe discomfort'`
  - `'palpitations'`
  - `'faint'`
- **Processing:** Agent performs natural language analysis to detect concerning symptom reports
- **Output Requirement:** Extract exact flagged symptom text with patient IDs

**Expected Output Format:**
```
Patient P001: No critical symptoms reported
Patient P002: Flagged symptoms - "chest pain" and "dizzy"
Patient P004: Flagged symptoms - "palpitations" and "dizziness"
...
```

### 3. **Reporting Task** (`reporting_task`)

**Assigned Agent:** `clinical_reporter` (Clinical Summary Generator)

**Task Description Breakdown:**
- **Input Sources:** Receives outputs from BOTH previous tasks via `context=[vital_analysis_task, symptom_check_task]`
- **Synthesis Role:** Combines findings from both analyses into unified patient-by-patient report
- **Format Requirement:** Must output **only** Markdown-formatted report
- **Structure:** Each patient gets their own section with complete findings

**Expected Output Format:**
```markdown
### Patient ID: P001
- No immediate concerns noted for this patient.

### Patient ID: P002  
- Flagged Vital Signs: Resting HR: 95 bpm, Total Steps: 1800
- Flagged Symptoms: Reported 'chest pain' and 'dizzy'

### Patient ID: P003
- No immediate concerns noted for this patient.
```

## Key Task Design Principles

### **Sequential Dependency**
```python
context=[vital_analysis_task, symptom_check_task]
```
- The `reporting_task` **depends on** the outputs of the first two tasks
- CrewAI ensures vital signs and symptom analyses complete **before** report generation starts
- This creates a proper data flow: Raw Data → Analysis → Synthesis

### **Template Variables**
```python
"{patient_data_input_str}"
```
- This placeholder gets replaced with actual patient data when `crew.kickoff(inputs={...})` is called
- Ensures all agents receive the same source data for consistency

### **Agent Specialization**
Each task is matched to an agent's expertise:
- **Numerical analysis** → Vital Signs Analyzer
- **Text processing** → Symptom Checker  
- **Report generation** → Clinical Reporter

### **Output Standardization**
- Each `expected_output` provides clear formatting examples
- Helps the LLM understand exactly what structure to produce
- Ensures consistent results across different runs

## Workflow Execution Order

1. **Step 1:** `vital_analysis_task` processes numerical thresholds
2. **Step 2:** `symptom_check_task` analyzes text for keywords  
3. **Step 3:** `reporting_task` synthesizes both analyses into final Markdown report

This design demonstrates CrewAI's strength in creating **modular, specialized workflows** where each agent contributes their expertise to a larger collaborative goal - exactly what's needed for complex healthcare data analysis in eHjerteRehab.


In [6]:
# Define the task for analyzing vital signs
vital_analysis_task = Task(
    description=(
        "Analyze the following patient data summaries for vital signs concerns:\n"
        "------\n"
        "{patient_data_input_str}\n"
        "------\n"
        "Identify patients with resting heart rate (avg_resting_hr_last_24h) > 90 bpm OR total steps (total_steps_last_24h) < 2000. "
        "For each patient, list their ID and the specific vital sign(s) that are flagged with their values."
        "If no vital signs are flagged for a patient, note that."
    ),
    expected_output=(
        "A textual summary listing each patient ID and any flagged vital signs with their values, or a note if no vital signs are flagged for that patient."
    ),
    agent=vital_signs_analyzer
)

# Define the task for checking symptoms
symptom_check_task = Task(
    description=(
        "Analyze the 'reported_symptoms_text' for each patient in the following data summaries:\n"
        "------\n"
        "{patient_data_input_str}\n"
        "------\n"
        "Identify patients who report symptoms containing keywords: 'chest pain', 'dizzy', 'dizziness', 'severe discomfort', 'palpitations', 'faint'. "
        "For each patient, list their ID and the exact flagged symptom text."
        "If no critical symptoms are reported for a patient, note that."
    ),
    expected_output=(
        "A textual summary listing each patient ID and any reported critical symptoms, or a note if no critical symptoms are reported for that patient."
    ),
    agent=symptom_checker
)

# Define the task for generating the report
reporting_task = Task(
    description=(
        "Combine the vital signs analysis and symptom check analysis into a single, concise Markdown report. "
        "The report should have a section for each patient. "
        "For each patient, clearly state their ID, then list any flagged vital signs (with values) from the vital signs analysis, "
        "and any flagged symptoms from the symptom check analysis. "
        "If a patient has no flags from either analysis, state 'No immediate concerns noted for this patient.' "
        "Ensure the final output is ONLY the Markdown report, ready for display."
    ),
    expected_output=(
        "A comprehensive Markdown report summarizing all findings for each patient. "
        "Example for one patient:\n"
        "### Patient ID: P00X\n"
        "- Flagged Vital Signs: Resting HR: 95 bpm, Total Steps: 1500\n"
        "- Flagged Symptoms: Reported 'chest pain during activity'.\n"
        "(If no flags: ### Patient ID: P00Y\n - No immediate concerns noted for this patient.)"
    ),
    agent=clinical_reporter,
    context=[vital_analysis_task, symptom_check_task] # Depends on the output of the previous two tasks
)

----

## Crew Instantiation and Kickoff

Show how to assemble the crew and run it.

In [7]:
# Instantiate the crew with a sequential process
ehcardialrehab_crew = Crew(
    agents=[vital_signs_analyzer, symptom_checker, clinical_reporter],
    tasks=[vital_analysis_task, symptom_check_task, reporting_task],
    process=Process.sequential,
    verbose=False # Use Truefor detailed crew-level logging
)

# Kick off the crew's work
# The input dictionary key 'patient_data_input_str' must match the placeholder in the task descriptions
results = ehcardialrehab_crew.kickoff(inputs={'patient_data_input_str': patient_data_summary_str})

# Print the final result from the crew
print("\n\n--- Final Report ---")
print(results)

# Agent: Vital Signs Monitoring Specialist
## Task: Analyze the following patient data summaries for vital signs concerns:
------
{'patient_id': 'P001', 'avg_resting_hr_last_24h': 72, 'max_hr_during_exercise_last_24h': 135, 'total_steps_last_24h': 8500, 'reported_symptoms_text': 'Feeling good today. Completed my morning walk without any issues. Energy levels are stable.'}
{'patient_id': 'P002', 'avg_resting_hr_last_24h': 95, 'max_hr_during_exercise_last_24h': 165, 'total_steps_last_24h': 1800, 'reported_symptoms_text': 'Woke up with some chest pain, but it passed. Feeling a bit dizzy today after climbing stairs.'}
{'patient_id': 'P003', 'avg_resting_hr_last_24h': 68, 'max_hr_during_exercise_last_24h': 142, 'total_steps_last_24h': 5200, 'reported_symptoms_text': 'Overall doing well. Some mild fatigue but nothing concerning. Appetite is good.'}
{'patient_id': 'P004', 'avg_resting_hr_last_24h': 88, 'max_hr_during_exercise_last_24h': 158, 'total_steps_last_24h': 1500, 'reported_symptoms_te



# Agent: Vital Signs Monitoring Specialist
## Final Answer: 
- Patient ID: P002  
  Flagged Vital Signs:  
  - Avg Resting HR: 95 bpm  
  - Total Steps: 1800 steps  

- Patient ID: P004  
  Flagged Vital Signs:  
  - Avg Resting HR: 88 bpm  
  - Total Steps: 1500 steps  

- Patient ID: P005  
  Flagged Vital Signs:  
  - Avg Resting HR: 102 bpm  

- Patient ID: P006  
  Flagged Vital Signs:  
  - Total Steps: 950 steps  

- Patient ID: P008  
  Flagged Vital Signs:  
  - Avg Resting HR: 93 bpm  

Patients P001, P003, and P007 have no flagged vital signs.


# Agent: Patient Symptom Screener
## Task: Analyze the 'reported_symptoms_text' for each patient in the following data summaries:
------
{'patient_id': 'P001', 'avg_resting_hr_last_24h': 72, 'max_hr_during_exercise_last_24h': 135, 'total_steps_last_24h': 8500, 'reported_symptoms_text': 'Feeling good today. Completed my morning walk without any issues. Energy levels are stable.'}
{'patient_id': 'P002', 'avg_resting_hr_last_24h': 95,

--- Final Report ---

### Patient ID: P002
- Flagged Vital Signs: Avg Resting HR: 95 bpm, Total Steps: 1800 steps
- Flagged Symptoms: 'Woke up with some chest pain, but it passed. Feeling a bit dizzy today after climbing stairs.'

### Patient ID: P004
- Flagged Vital Signs: Avg Resting HR: 88 bpm, Total Steps: 1500 steps
- Flagged Symptoms: 'Had some palpitations during exercise yesterday. Also experienced dizziness when standing up quickly.'

### Patient ID: P005
- Flagged Vital Signs: Avg Resting HR: 102 bpm
- Flagged Symptoms: 'Feeling anxious about my recovery. Some shortness of breath during light activities.'

### Patient ID: P006
- Flagged Vital Signs: Total Steps: 950 steps
- Flagged Symptoms: 'Feeling tired, slight chest discomfort during stairs. Had to rest more than usual.'

### Patient ID: P008
- Flagged Vital Signs: Avg Resting HR: 93 bpm
- Flagged Symptoms: 'Some severe discomfort in my chest area this morning. Also felt faint briefly around noon.'

### Patient ID: P001
- No immediate concerns noted for this patient.

### Patient ID: P003
- No immediate concerns noted for this patient.

### Patient ID: P007
- No immediate concerns noted for this patient.


## Crew Creation and Execution: Detailed Explanation

### **Crew Instantiation** 
```python
ehcardialrehab_crew = Crew(
    agents=[vital_signs_analyzer, symptom_checker, clinical_reporter],
    tasks=[vital_analysis_task, symptom_check_task, reporting_task],
    process=Process.sequential,
    verbose=False
)
```

**Crew Components Breakdown:**

#### **`agents=[]` Parameter**
- **Purpose**: Defines the team members (AI agents) that will collaborate on the workflow
- **Order**: The list order doesn't dictate execution sequence - that's determined by task dependencies
- **Composition**: Our three specialized agents:
  - `vital_signs_analyzer` - Numerical data analysis specialist
  - `symptom_checker` - Text processing and keyword detection expert  
  - `clinical_reporter` - Report synthesis and Markdown formatting specialist

#### **`tasks=[]` Parameter**
- **Purpose**: Defines the specific work items to be completed by the crew
- **Task Assignment**: Each task is pre-assigned to a specific agent via the `agent=` parameter
- **Dependencies**: Task execution order is determined by `context=[]` dependencies, not list position
- **Workflow**: Our three-step process:
  1. `vital_analysis_task` → Analyze numerical thresholds
  2. `symptom_check_task` → Process symptom text
  3. `reporting_task` → Synthesize findings (depends on first two)

#### **`process=Process.sequential`**
- **Execution Model**: Tasks run one after another in dependency order
- **Alternative**: `Process.hierarchical` would add a manager agent to coordinate workflow
- **Benefit**: Ensures data flows properly from analysis → synthesis → final output
- **Synchronization**: Each task completes fully before dependent tasks begin

#### **`verbose=False`**
- **Logging Control**: Determines how much execution detail is displayed
- **Options**:
  - `verbose=False` → Clean output, shows only final results ✅ (current setting)
  - `verbose=True` → Detailed logging showing agent "thinking" process, tool usage, and intermediate outputs
- **Development Tip**: Use `verbose=True` for debugging and understanding agent behavior

### **Crew Execution with `kickoff()`**
```python
results = ehcardialrehab_crew.kickoff(inputs={'patient_data_input_str': patient_data_summary_str})
```

#### **Starting the Workflow**
- **Method**: `kickoff()` is CrewAI's execution trigger that starts the collaborative workflow
- **Initialization**: Activates all agents and begins processing the first task in the dependency chain
- **Data Flow**: Ensures input data reaches the appropriate tasks through template substitution

#### **The `inputs={}` Dictionary**
- **Purpose**: Provides initial data that gets injected into task descriptions
- **Template Matching**: The key `'patient_data_input_str'` must exactly match the placeholder `{patient_data_input_str}` used in task descriptions
- **Data Injection**: CrewAI replaces all instances of `{patient_data_input_str}` with the actual patient data string
- **Consistency**: This ensures all agents receive identical source data for their analysis

#### **Template Substitution Process**
```python
# Before kickoff (in task descriptions):
"Analyze the following patient data summaries:\n{patient_data_input_str}\n"

# After kickoff (what agents actually receive):
"Analyze the following patient data summaries:\n{'patient_id': 'P001', 'avg_resting_hr_last_24h': 72, ...}\n"
```

### **Expected Output: Comprehensive Markdown Report**

#### **Format Characteristics**
- **Structure**: Patient-by-patient breakdown with clear headings
- **Content**: Combines findings from both vital signs analysis and symptom checking
- **Presentation**: Ready-to-display Markdown that can be rendered in notebooks, web apps, or documentation

#### **Sample Expected Output**
```markdown
### Patient ID: P002
- Flagged Vital Signs: Avg Resting HR: 95 bpm, Total Steps: 1800 steps
- Flagged Symptoms: "Woke up with some chest pain, but it passed. Feeling a bit dizzy today after climbing stairs."

### Patient ID: P001
- No immediate concerns noted for this patient.

### Patient ID: P008  
- Flagged Vital Signs: Avg Resting HR: 93 bpm
- Flagged Symptoms: "Some severe discomfort in my chest area this morning. Also felt faint briefly around noon."
```

#### **Clinical Value**
- **Actionable Intelligence**: Immediately highlights patients requiring clinical attention
- **Comprehensive Coverage**: No patient data is missed - all 8 patients get evaluated
- **Professional Format**: Ready for integration into clinical workflows or patient management systems
- **Prioritization**: Flagged patients stand out clearly from those with no concerns

### **Workflow Execution Summary**
1. **Initialization**: CrewAI loads agents and tasks, establishes dependencies
2. **Data Injection**: Patient data string replaces template placeholders
3. **Sequential Processing**: 
   - Vital Signs Analyzer processes numerical data
   - Symptom Checker analyzes text data  
   - Clinical Reporter synthesizes both analyses
4. **Output Generation**: Final Markdown report returned as `results` variable
5. **Display**: Report printed for immediate review and action

This orchestrated approach demonstrates how CrewAI transforms complex, multi-step healthcare data analysis into a streamlined, automated workflow that maintains the specialized expertise of different analytical domains while ensuring comprehensive patient coverage.


## Interpreting the Output and Next Steps

The output from this demo crew will be a Markdown-formatted string containing the clinical summary report. It should list each patient from the simulated data, highlighting any flagged vital signs, e.g.,

- "Patient P002: Flagged Vital Signs: Resting HR: 98 bpm, Total Steps: 1800"

and any critical reported symptoms, e.g., 

- "Patient P002: Flagged Symptoms: Woke up with some chest pain, but it passed. Feeling a bit dizzy today."

Patients with no flags would be noted as having "No immediate concerns."

This simple prototype demonstrates the fundamental capability of CrewAI to orchestrate multiple AI agents to perform a multi-step analysis and reporting task relevant to eHjerteRehab.

### Next Steps for Expansion:
This basic prototype can be significantly expanded to move closer to the comprehensive eCardialRehab agent system envisioned:

#### Real Data Integration: 

Connect agents to actual data sources (databases, APIs for wearables, EHRs) using appropriate crewai_tools (e.g., DatabaseTool, custom API tools) instead of simulated data.

#### Sophisticated Tools: 

Equip agents with more advanced tools. For instance, the Risk Assessment Agent could use the CodeInterpreterTool to run complex ML models for risk scoring, or a custom tool that queries a medical knowledge graph. The SymptomCheckerAgent could use tools leveraging more advanced NLP models for nuanced symptom understanding rather than simple keyword matching.


#### More Specialized Agents: 
Introduce additional agents (e.g., a PersonalizedContentAgent that uses the report from the ClinicalReporterAgent to suggest interventions).

- **Hierarchical Process**: For more complex patient management scenarios, implement a Process.hierarchical model where a "ClinicalManagerAgent" coordinates the other agents, assigns tasks dynamically, and reviews outputs before final action.

- **Robust Error Handling**: Implement comprehensive error handling within agent tasks and tool interactions to manage API failures, data inconsistencies, or unexpected LLM outputs.

- **State Management**: For long-running interactions or more complex patient journeys, incorporate more sophisticated state management to maintain context across multiple crew executions or patient interactions.

- **Integration with MLOps** (*set of practices and tools that combine machine learning, software engineering and DevOps principles to automate and streamline the end-to-end lifecycle of ML models, from development and deplayment to monitoring and maintainance*): If agents utilize ML models (e.g., for risk prediction), integrate the system with MLOps pipelines for model versioning, monitoring for performance degradation or data drift, and facilitating retraining cycles. 

This is critical for maintaining the accuracy and reliability of AI-driven insights in a production healthcare environment. Moving from a Jupyter notebook demonstration to a production-grade eCardialRehab system requires careful consideration of these operational aspects, which are beyond the scope of a simple kickoff() but are essential for the technical manager to plan for in the actual deployment of the eCardialRehab project.

### Conclusion

**Recap of AI's Transformative Impact on eCardialRehab**

The integration of Artificial Intelligence holds the promise of fundamentally transforming cardiac eRehabilitation platforms like eCardialRehab. As explored, AI agents, orchestrated by frameworks such as CrewAI, can create a collaborative intelligence layer capable of automating complex monitoring, analysis, and communication tasks. Advanced data analysis, powered by machine learning techniques for pattern recognition in physiological and behavioral data, and natural language processing for understanding patient narratives, can unlock deeper, more nuanced insights into each patient's unique condition and progress. Furthermore, AI-driven communication tools, including intelligent clinician dashboards and personalized patient feedback systems, can make the rehabilitation journey more efficient for clinicians and more engaging and supportive for patients. Collectively, these AI methodologies can shift eCardialRehab from a static content delivery platform to a dynamic, adaptive, and proactive system that offers truly personalized care, enhances patient adherence, and ultimately aims to improve clinical outcomes.

## Future Outlook and Recommendations for AI Integration

The journey towards a fully AI-integrated eCardialRehab platform should be approached strategically and incrementally.

- **Phased Implementation**: It is advisable to begin with foundational AI capabilities. This could involve establishing robust data collection pipelines for wearables and PROs, followed by the development of initial AI agents for data monitoring and basic risk flagging (similar to the prototype). Subsequently, more sophisticated analytical models (ML for predictive risk, NLP for feedback analysis) and more autonomous agent functionalities (e.g., personalized content suggestion, hierarchical task management) can be progressively layered into the system.

- **Ethical Considerations and Data Governance**: Throughout the development and deployment lifecycle, paramount importance must be given to ethical considerations, patient data privacy, and security. Compliance with healthcare data regulations (e.g., GDPR, HIPAA) is non-negotiable. Transparent policies regarding data usage and AI decision-making processes should be established.

- **Human-in-the-Loop (HITL) as a Core Principle**: Especially for clinical decision support and patient communication involving medical advice, the HITL principle must be embedded. AI should augment, not replace, human clinicians. Mechanisms for clinician review, override, and validation of AI-generated insights or recommendations are crucial for ensuring patient safety and maintaining trust in the system.

- **Continuous Learning and Adaptation**: The field of AI is rapidly evolving. The eHjerteRehab platform should be designed with adaptability in mind, allowing for the integration of new AI techniques, tools, and models as they mature and demonstrate value. This includes establishing processes for ongoing monitoring of AI model performance, retraining as necessary, and gathering feedback from both clinicians and patients to iteratively refine the AI components.

- **Focus on Explainability (XAI)**: To foster clinician adoption and trust, efforts should be made to incorporate XAI techniques, particularly for AI components involved in risk assessment or clinical recommendations. Understanding the "why" behind an AI's output is critical in healthcare.

By embracing these principles, eCardialRehab can harness the transformative power of AI to deliver a new generation of cardiac eRehabilitation that is more personalized, proactive, efficient, and ultimately, more effective in supporting patients on their journey to recovery and long-term cardiovascular health.

**Refs**


cloud.google.com
What are AI agents? Definition, examples, and types | Google Cloud


github.com
stephenc222/example-crewai: Example project demonstrating CrewAI - GitHub


docs.crewai.com
Tasks - CrewAI


aimasterclass.com
What is Collaborative Multi-Agent Systems? - AI Master Class


docs.crewai.com
Crafting Effective Agents - CrewAI


github.com
crewAI-examples/prep-for-a-meeting/main.py at main - GitHub


news-medical.net
Mayo Clinic develops AI tool to visualize complex biological data - News-Medical.net


quadratichq.com
The Importance of AI Data Analysis in Healthcare - Quadratic


thoughtful.ai
How AI-Powered Solutions Enhance Patient Experience - Thoughtful AI


pinc-ai.com
Clinical Decision Support Analytics - Stanson Health - PINC AI


lumenalta.com
9 examples of natural language processing in healthcare | NLP in healthcare - Lumenalta


eithealth.eu
Machine learning in healthcare: Uses, benefits and pioneers in the field - EIT Health


relias.com
AI in Patient Experience: Top 4 AI Use Cases in Healthcare | Relias


akira.ai
How AI Agents are Transforming Rehabilitation Monitoring in ...


digiqt.com
Is Your Clinic Ready for AI Agents in Physical Therapy? | Digiqt Blog


getondata.com
AI-powered dashboards for healthcare: The modern medical edge


reddit.com
What programs and software do I need to get started? : r/crewai

foreseemed.com
Machine Learning in Healthcare: Guide to Applications & Benefits


pmc.ncbi.nlm.nih.gov
Natural Language Processing to Extract Meaningful Information from ...


community.crewai.com
Suggested cursorrules template for working with CrewAI - General ...


cohorte.co
The Friendly Developer's Guide to CrewAI for Support Bots & Workflow Automation


basishealth.io
Personalized Health Dashboards: Design Guide & Best Practices | Basis Blog


mdpi.com
Deep Learning for Predicting Rehabilitation Success: Advancing Clinical and Patient-Reported Outcome Modeling - MDPI


app.uxcel.com
Dashboard Design for Health Platform Brief - Uxcel

researchgate.net
Machine Learning-Based Prediction Models for Healthcare Outcomes in Patients Participating in Cardiac Rehabilitation: A Systematic Review | Request PDF - ResearchGate


alejandro-ao.com
Crew AI Crash Course (Step by Step) - Alejandro AO
 

inspireresearch.com
Inspire Launches AI-Enabled Patient Insights | Transforming Life Sciences Research
 

okoone.com
What generative AI means for the future of healthcare | Okoone
 

thoughtspot.com
The Human-in-the-Loop Approach: Bridging AI & Human Expertise - ThoughtSpot
 

1000minds.com
What is Human-in-the-loop (HITL) in AI-assisted decision-making? - 1000minds
 

github.com
generative-ai/gemini/agent-engine ... - GitHub
 

docs.crewai.com
Quickstart - CrewAI
 

ai.google.dev
Customer Support Analysis with Gemini 2.5 Pro and CrewAI
 

mdpi.com
Comparative Analysis of Machine Learning Techniques for Heart Rate Prediction Employing Wearable Sensor Data - MDPI
 

ascopubs.org
Using Machine Learning to Predict Unplanned Hospital Utilization and Chemotherapy Management From Patient-Reported Outcome Measures | JCO Clinical Cancer Informatics - ASCO Publications
 

researchgate.net
Comparative Analysis of Machine Learning Techniques for Heart Rate Prediction Employing Wearable Sensor Data - ResearchGate
 

ibm.com
What is crewAI? - IBM
 

docs.crewai.com
Processes - CrewAI
 

pmc.ncbi.nlm.nih.gov
Population-Based Applications and Analytics Using Patient-Reported Outcome Measures - PMC - PubMed Central
 

docs.crewai.com
Agents - CrewAI
 

docs.crewai.com
Build Your First Crew - CrewAI
 

researchgate.net
(PDF) Creating a Comprehensive AI-Driven Risk Stratification Tool for High-Risk Heart Failure Populations - ResearchGate
 

arkenea.com
3 Compelling Cases of AI-Driven Patient Risk Stratification Tools - Arkenea
 

beyondkey.com
Healthcare Dashboard Examples | Beyond Key
 

github.com
alexfazio/crewAI-quickstart: A collection of notebooks ... - GitHub
 

aws.amazon.com
Build agentic systems with CrewAI and Amazon Bedrock | AWS ...
 

uibakery.io
10 Free Healthcare Dashboard Templates for Medical Data Management | UI Bakery Blog
 

upsolve.ai
10 Healthcare Dashboard Examples + Key Metrics To Track in 2025 - Upsolve AI
 

jmai.amegroups.org
Development and validation of a data visualization dashboard for automatic pain assessment and artificial intelligence analyses in cancer patients
 

thebricks.com
Clinical and Psychosocial Profile Dashboard Template - Bricks


Sources read but not used in the report
